<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Video </title>
    <?php
    include "include/header.php";
    ?>
</head>

<body>
    <section>
        <div class="video-banner-box">
            <div class="video-banner-thumbnail">
                <div class="video-banner-img-box">
                    <img class="video-banner-img" src="assets/images/video-banner.png" alt="">
                </div>
                <div class="banner-header-title">Video</div>
            </div>
        </div>
    </section>
    <section class="section-margin">
        <h3 class="primary-heading">Video Gallery</h3>
        <div class="container">

                <div class="video-carousel-controls">
                    <button
                        class="video-carousel-btn"
                        id="video-carousel-prev"
                        type="button"
                    >
                        <span
                        ><img
                            class="video-carousel-btn-icon"
                            src="assets/images/icon/back.png"
                            alt="Previous"
                        /></span>
                    </button>
                    <button
                        class="video-carousel-btn"
                        id="video-carousel-next"
                        type="button"
                    >
                        <span
                        ><img class="video-carousel-btn-icon" src="assets/images/icon/next.png" alt="Next"
                        /></span>
                    </button>
                </div>
                <div class="owl-carousel owl-theme" id="video-carousel">
                <!-- Video items will be generated by JavaScript -->
                </div>

                <div id="videoModal" class="video-modal">
                    <div class="video-modal-content">
                        <span class="video-modal-close" onclick="closeVideoModal()"
                        ><i class="fas fa-times"></i
                        ></span>
                        <iframe
                        id="videoPlayer"
                        frameborder="0"
                        allow="autoplay; fullscreen"
                        allowfullscreen
                        ></iframe>
                    </div>
                </div>
        </div>
    </section>

    <?php
    include "include/footer.php";
    ?>
</body>

</html>